README.md

Pull Request for Sprint 1. Modified README.

Sprint 1 pull request

---

FrontEnd/Website/html&css_template/forum_page.html
FrontEnd/Website/html&css_template/global.css

On a given forum page, the user profile data (date, time, username,
points) is displayed next to the question he/she asked.

Added the "user who asked" element to the question

---

FrontEnd/Website/html&css_template/forum_page.html
FrontEnd/Website/html&css_template/global.css

The answers section was completely implemented in html/css. Please see the commit attached to this branch for more details

Answers section

---

FrontEnd/Website/html&css_template/global.css
FrontEnd/Website/html&css_template/home_page.html
FrontEnd/Website/html&css_template/script.js
FrontEnd/Website/html&css_template/sign_up.html

I wrote a footer. however it's the big lines, and an acceptable I guess. The rest is just to link to you guy's pages and it's all good. 
BTW, do you guys want to have a logo for our website, and do you guys want to have a fb, twiter like page for people to follow.

Footer and it's css

---

FrontEnd/Website/html&css_template/sign_up.html

Updated sign_up page

---

FrontEnd/Website/html&css_template/global.css
FrontEnd/Website/html&css_template/home_page.html

- Added color
- Fix margins
- Added animations on the number of votes, answers and views

Updated the CSS for the homepage

---

FrontEnd/Website/html&css_template/Login_page.html
FrontEnd/Website/html&css_template/ask_question.html
FrontEnd/Website/html&css_template/contact.html
FrontEnd/Website/html&css_template/forum_page.html
FrontEnd/Website/html&css_template/global.css
FrontEnd/Website/html&css_template/home_page.html
FrontEnd/Website/html&css_template/sign_up.html
FrontEnd/Website/html&css_template/user_profile.html

A basic ask page was added along with the addition of a footer on each
page

Added footer to all pages + Ask page

---

FrontEnd/Website/html&css_template/Login_page.html
FrontEnd/Website/html&css_template/global.css

Changed CSS & HTML of Login page in order to follow color scheme of the other pages of the website.

Saleh login transfer sprint 1

---

FrontEnd/Website/public/scripts/script.js
FrontEnd/Website/public/stylesheets/contact-stylesheet.css
FrontEnd/Website/public/stylesheets/global.css
FrontEnd/Website/public/stylesheets/login-stylesheet.css
FrontEnd/Website/public/stylesheets/signup-stylesheet.css
FrontEnd/Website/views/partials/footer.ejs
FrontEnd/Website/views/partials/header.ejs
README.md

Created header/footer partials. Moved css and scripts into their own folder

Creation of header/footer partials and public folder

---

FrontEnd/Website/views/partials/header.ejs

Added About us tab in the nav bar (not functional at the moment).
Changed Contact us page name to reflect its correct tittle

Updated header.ejs

---

FrontEnd/Website/app.js

Updated app.js with post/get connections to contact.ejs

Alex   Contact Us

---

FrontEnd/Website/views/partials/header.ejs

updated header.ejs to include correct path connection to about us page

Alex  About us

---

FrontEnd/Website/app.js
FrontEnd/Website/views/search_page.ejs

Adding non-dynamic search page and its get function in app.js

Adding search page

---

FrontEnd/Website/views/about.ejs

Converted about.html to a new about.ejs  with some code refactored

Created about ejs file

---

FrontEnd/Website/public/stylesheets/global.css

Updated the correct global css

Updated global css

---

FrontEnd/Website/app.js
FrontEnd/Website/views/partials/header.ejs
FrontEnd/Website/views/sign_up.ejs

added code to app.js to support sign_up.ejs file

 updated app.js for signup page request

---

BackEnd1/Queries/ReadMe.txt
BackEnd1/Queries/add_new_user.js
BackEnd1/Queries/get_user_answer.js
BackEnd1/Queries/get_user_info.js
BackEnd1/Queries/get_user_question.js
BackEnd1/Queries/store_answer.js
BackEnd1/Queries/store_question.js
BackEnd1/Queries/store_score_answer.js
BackEnd1/Queries/store_score_question.js

Most of the BackEnd code started. 
Need to take values from the GET and POST from the front end and inserted in there once completed. 
There are still fixes that need to be done, will work on it over the weekend. 
Note from ReadMe:
"This is still work in progress. Need some fixes, but currently can be used for queries if you copy-past string inside 'var SQL' into your MySQL command line.
Will explain how to use it once I'm done . "

Saleh backend1

---

FrontEnd/Website/app.js
FrontEnd/Website/views/login_page.ejs

Added login_page view & added the Get & Post Method for for the login page

Saleh front end

---

FrontEnd/Website/views/partials/header.ejs
FrontEnd/Website/views/search_page.ejs

"Help?" link was removed from the navbar.
It contained a dropdown menu with dead links and was only there for palceholder.

Commented out the help dropdown menu in the navbar

---

FrontEnd/Website/views/partials/header.ejs

Search bar will return error message to user if the searched item is less than 1 char or more than 100 char.
Done via HTML validation.

Restricted search bar to 1-100 characters

---

FrontEnd/Website/app.js
FrontEnd/Website/views/about.ejs
FrontEnd/Website/views/login_page.ejs
FrontEnd/Website/views/partials/header.ejs
FrontEnd/Website/views/search_page.ejs

Refactoring of app.js and navbar code to account for changes while migrating to .ejs.

Connected login page to server. Fixed about and login URL in navbar

---

FrontEnd/Website/app.js

update for app.js

---

Database/Node.js-MySQL/Connect Node.js to MySQL.txt
Database/Node.js-MySQL/DBconnection.js
Database/Node.js-MySQL/Database Manipulation .js files/createDB.js
Database/Node.js-MySQL/Database Manipulation .js files/createTable.js
Database/Node.js-MySQL/Database Manipulation .js files/deleteRecord.js
Database/Node.js-MySQL/Database Manipulation .js files/dropTable.js
Database/Node.js-MySQL/Database Manipulation .js files/getRecord.js
Database/Node.js-MySQL/Database Manipulation .js files/insertData.js
Database/Node.js-MySQL/Database Manipulation .js files/insertMulti.js
Database/Node.js-MySQL/Database Manipulation .js files/readme.txt
Database/Node.js-MySQL/Database Manipulation .js files/updateRecord.js
Database/Node.js-MySQL/package-lock.json
Database/Node.js-MySQL/package.json
README.md

Database .js files + config files for connection Node.js and MySQL

Nizar belhassan

---

BackEnd1/Queries/ReadMe.txt
BackEnd1/Queries/add_new_user.js
BackEnd1/Queries/get_user_answer.js
BackEnd1/Queries/get_user_info.js
BackEnd1/Queries/get_user_question.js
BackEnd1/Queries/store_answer.js
BackEnd1/Queries/store_question.js
BackEnd1/Queries/store_score_answer.js
BackEnd1/Queries/store_score_question.js

Fixed all "get" queries. 
Eliminated all duplicate output from queries by adding "DISTINCT" inside js files.

Minor updates on sql queries

---

FrontEnd/Website/app.js
FrontEnd/Website/views/forum_page.ejs
FrontEnd/Website/views/sign_up.ejs

Major updates on app.js file to include queries from database are implemented, check each commit for more details.
Some minor modifications on sign_up and forum_page ejs files  for database queries implementation.

Latest version of functional Webpage

---

FrontEnd/Website/routes/ask_page.js
FrontEnd/Website/routes/forum_page.js

Modification of the last query, sql3.
Added a connection of question  with user table, where the query gets
all the question ids from the question table that are from the user id
specified (in our case the user who asked the question)
Lastly, after success on posting a question, the system redirects the
user to a forum page of his/her new question asked.
Also, some code refactoring to make  code in ask and forum page more readable

Alex new changes

---

FrontEnd/Website/app.js
FrontEnd/Website/public/stylesheets/global.css
FrontEnd/Website/routes/ask_page.js
FrontEnd/Website/routes/forum_page.js
FrontEnd/Website/routes/homepage.js
FrontEnd/Website/views/ask.ejs
FrontEnd/Website/views/forum_page.ejs
FrontEnd/Website/views/homepage.ejs
FrontEnd/Website/views/partials/header.ejs
FrontEnd/Website/views/partials/notlogged.ejs

See #205. The user will now be asked to log-in if they access the "Ask"
page, or if they desire to "Answer" a question on any of the forum
pages. Also, all forms now send the user-id who filled it out to the
back-end for use with database queries.

Added Ask & Answer Login Compliance

---

FrontEnd/Website/views/about.ejs

Fixed capitalization and a lacking "s" in a word.

Fixed some really small spelling/grammar errors in the About page

---

FrontEnd/Website/routes/search_page.js
FrontEnd/Website/views/search_page.ejs

Search page should now display the searched item at the top of the page and before the results.

Passed the search string to the search page so that it display on top of all the results. JS and EJS modified.

---

FrontEnd/Website/routes/homepage.js
FrontEnd/Website/routes/userprofile_page.js

Changed variable num_of_questions on homepage.js to correctly get the lenght of the result from the question table.
Code refactoring to make home page and user profile to display the correct date and time based on the right time zone.

Fixed date time display

---

FrontEnd/Website/app.js
FrontEnd/Website/public/scripts/vote_communication.js
FrontEnd/Website/routes/forum_page.js
FrontEnd/Website/routes/vote.js
FrontEnd/Website/views/forum_page.ejs
FrontEnd/Website/views/homepage.ejs
FrontEnd/Website/views/user_profile.ejs

The up and down ticks for each question and respective answer(s) are now
clickable (IFF logged in), and send the relevant information to the
back-end for possibly incrementing and decrementing the total score for
that question/answer. The vote route can be found in ../routes/vote.js
and is basically set-up for use with a query under development by @SAA9

Added back-end voting system

---

FrontEnd/Website/test/ReadMe.txt

File contains simple instruction of what to install and what command lines arguments to enter.

Added a small ReadMe file to the frontend test folder to help those who wish to run the tests locally on their PCs

---

FrontEnd/Website/test/ask.test.js
FrontEnd/Website/test/contact.test.js
FrontEnd/Website/test/login.test.js
FrontEnd/Website/test/search.test.js
FrontEnd/Website/test/signup.test.js

Includes modifications to the test.js files to check if the forms are posting correctly.
Tests created for Contact, Ask, Login, Signup pages.
Ask pages produces an error. Requires more DB knowledge to fix, but the test still shows up when they run.

Tests for the page POST request

---

FrontEnd/Website/app.js
FrontEnd/Website/routes/contact_page.js
FrontEnd/Website/routes/login_page.js
FrontEnd/Website/views/contact.ejs
FrontEnd/Website/views/email_user.ejs
FrontEnd/Website/views/email_website.ejs

Added HTML + CSS emails, and updated the contact js and ejs files. Email is sent to website owner whenever user submits form in contact page. A confirmation email is also sent to user so that they can see what they sent. User information is automatically filled if they are already logged in using their cookie information.

Improved Email Functionality for contact page

---

.travis.yml
test/README

modified the path for the script on the .travis.yml

modification on the travis to direct the path to the test

---

FrontEnd/Website/routes/search_page.js
FrontEnd/Website/views/partials/header.ejs
FrontEnd/Website/views/search_page.ejs

The user is able to search for a specific keyword in the search bar. Once the keyword has been submitted, the user is redirected to the search_page.ejs. Also, he/she is also able to click on a question to be redirected to the forum page to view the answers. The keyword minimum character limit is 3.

Added search functionality

---

FrontEnd/Website/routes/search_page.js
FrontEnd/Website/routes/userprofile_page.js
FrontEnd/Website/views/search_page.ejs

If no result is returned from the search, a message is outputted to let the user know.
Also, the username link functionality on the search page has been added.

Added search condition

---

FrontEnd/Website/public/scripts/sign_up.js
FrontEnd/Website/views/sign_up.ejs

Added javascript code for signup page validation. The sign_up.js file will check if user entered valid information when signing up and prevents user from sending the form if information is incorrect.

Abishand_Signup_Validation

---

FrontEnd/Website/views/after_signup.ejs
FrontEnd/Website/views/partials/header_after_sign_up.ejs

Created a new header that will fix bug #291 found by @jasonckc

Created a new header path for after_singup

---

FrontEnd/Website/routes/contact_page.js
FrontEnd/Website/test/about.test.js
FrontEnd/Website/test/ask.test.js
FrontEnd/Website/test/contact.test.js
FrontEnd/Website/test/login.test.js
FrontEnd/Website/test/search.test.js

Re-enabled and fixed the tests (ask, contact) that were failing and giving us issues.
Contact page still prints out an unidentified object error in its GET test, but it still passes since the objects are not required to reach the page. The POST test provides those objects and passes.

Get/Post Tests

---

FrontEnd/Website/routes/login_page.js
FrontEnd/Website/test/about.test.js
FrontEnd/Website/test/ask.test.js
FrontEnd/Website/test/contact.test.js
FrontEnd/Website/test/home.test.js
FrontEnd/Website/test/login.test.js
FrontEnd/Website/test/search.test.js
FrontEnd/Website/test/signup.test.js
FrontEnd/Website/test/userprofile.test.js

Changes the automated tests names so that they are more descriptive and and readable to non-team members.
Also commented out the "login page!" console log from the login page route to lessen the clutter that printed to the console when testing.

Test name changes

---

FrontEnd/Website/test/logout.test.js
FrontEnd/Website/test/vote.test.js

Wrote automated tests that check if the Log Out page redirects to the Home page, and if the the vote POST function is properly sending data.
Log Out page test is confirmed to work locally.
Vote page test does not work - I require input from the vote system creator (will discuss during meeting on March 22)

Added tests for the Vote and Log Out functionalities

---

Database/Raw Script (FYI)/All Notes on DB (fyi).txt
FrontEnd/Website/routes/forum_page.js
FrontEnd/Website/routes/vote.js
minutes/readme.md

The changes you find below was provided for the above 2 user story. 
1. For the User Story - Re Vote Functionality: 
You will find changes done to the vote.js file by adding Update queries. Contact Alex or Saleh if any question.
2. For the User Story - Questioner Selects Best Answer:
You will find front end & XML code done by Anthony on vote_communication.js & global.css.
For backend, you will find the code for this under an added post function router.post("/favorite", function(req, res) ). Contact Alex or Saleh if any question.

Completed code for: ReVote Functionality & Questioner Selects Best Answer 

---

FrontEnd/Website/routes/about_page.js
FrontEnd/Website/routes/contact_page.js
FrontEnd/Website/routes/signup_page.js

The code in the about. contact, and signup page was refactored according
to the team's self-made coding style decisions

Refactored code based on sprint4 code style

---

FrontEnd/Website/routes/homepage.js
FrontEnd/Website/routes/userprofile_page.js

The code in the homepage.ejs and user_profile.ejs was refractored accordingly to the team's coding style

Improved code quality

---

FrontEnd/Website/routes/logout.js
FrontEnd/Website/routes/search_page.js

Refactor code for search and logout javascript files to enforce the coding style selected for the project.

Abishand Refactor Code

---

FrontEnd/Website/test/login.test.js
FrontEnd/Website/test/signup.test.js
FrontEnd/Website/test/vote.test.js

Modified the vote test to also include testing the question voting. It now tests the ability to vote on questions and on answers.
Modified the login test to account for the possibility of the user trying to log into an account that does not exist.
Modified the sign up to account for the possibility of the user trying to sign up with an already existing email.

Additions to the vote, login, and sign up tests

---

FrontEnd/Website/routes/vote.js

Coding style applied.
Changed most variable names to lower camel case (except variable that are similar to column name used in the database & the results for queries).
Changed brackets  order.
Removed unecessary

Applied Coding-Style to Vote.js page

---

.travis.yml

Added table question and table answer for travis database.

Added table question and table answer for travis

---

FrontEnd/Website/routes/forum_page.js

Issue was that the favorite answer if from the database was not in the
db query. Problem was fixed and selected answer is now updating visually

Alex  Refactoring

---

.travis.yml

Added table score_answer and table score_question to travis database.

Added table score_question and table score_answer for travis database

---

FrontEnd/Website/routes/homepage.js
FrontEnd/Website/views/partials/header.ejs
FrontEnd/Website/views/partials/header_after_sign_up.ejs
FrontEnd/Website/views/partials/header_only.ejs

The coding has been improved to match the team's coding style and the question tab has been removed, as it was only there for testing purposes.

Refractoring the code and removed the question tab

---

FrontEnd/Website/test/ask.test.js
FrontEnd/Website/test/contact.test.js
FrontEnd/Website/test/login.test.js
FrontEnd/Website/test/signup.test.js
FrontEnd/Website/test/userprofile.test.js

Added tests that check for invalid and/or empty form data on all POST functions.
Test files changed:
-ask.test.js
-contact.test.js
-login.test.js
-signup.test.js
Tests are all confirmed to work locally, but might fail for other team members since there is no travis DB to base the tests around.

Added new tests to round out the test coverage
